import os
import glob
import re

def normalize_whitespace(text):
    return r'\s+'.join(re.escape(word) for word in text.split())

def replace_in_file(filepath, replacements):
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
    
    for pt, en in replacements.items():
        pattern = normalize_whitespace(pt)
        content = re.sub(pattern, en, content)

    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(content)

tutorial_replacements = {
    'Como prefere receber este serviço?': 'How do you prefer to receive this service?',
    'Alguma observação para esta sessão?': 'Any observations for this session?',
    'Clique nos dias e horas que deseja <strong>BLOQUEAR</strong> (marcar como indisponíveis). A agenda é gerada por defeito.': 'Click the days and times you wish to <strong>BLOCK</strong> (mark as unavailable). The agenda is generated by default.',
    'Selecione as Horas para Bloquear em': 'Select Times to Block on',
    'Complete estes dados para que o Paulo possa personalizar o seu treino.': 'Complete these details so Paulo can personalize your training.',
    'Por favor, descreva os seus problemas de saúde ou limitações físicas.': 'Please describe your health problems or physical limitations.',
    'Completei o tutorial de agendamento': 'I have completed the booking tutorial',
    'Completei o tutorial da App': 'I have completed the App tutorial',
    'Como fazer a sua Marcação': 'How to make your Booking',
    'Comece por <strong>escolher o tipo de serviço</strong> que procura: <strong>Osteopatia</strong> ou <strong>Treino</strong>.': 'Start by <strong>choosing the type of service</strong> you are looking for: <strong>Osteopathy</strong> or <strong>Training</strong>.',
    'Depois de escolher o serviço, verá um <strong>calendário mensal</strong>. Toque no dia que pretende para a sua sessão.': 'After choosing the service, you will see a <strong>monthly calendar</strong>. Tap the day you want for your session.',
    'Ao selecionar um dia, aparecerão os <strong>horários disponíveis</strong> para esse dia. Toque no horário que lhe convém para o selecionar.': 'Upon selecting a day, the <strong>available times</strong> for that day will appear. Tap the time that suits you to select it.',
    'Múltiplas Sessões': 'Multiple Sessions',
    'Pode reservar <strong>várias sessões de uma só vez</strong>! Selecione diferentes dias e horários — cada seleção fica guardada automaticamente.': 'You can book <strong>several sessions at once</strong>! Select different days and times — each selection is automatically saved.',
    'Os dias com sessões selecionadas ficam marcados com a cor dourada no calendário. Pode tocar novamente num horário para o desselecionar.': 'Days with selected sessions are marked in gold on the calendar. You can tap a time again to deselect it.',
    'Antes de confirmar, verá um <strong>resumo</strong> com todas as sessões selecionadas. Pode também adicionar uma <strong>nota opcional</strong> com observações para o Paulo.': 'Before confirming, you will see a <strong>summary</strong> of all selected sessions. You can also add an <strong>optional note</strong> with observations for Paulo.',
    'Use as notas para informar sobre lesões, preferências ou qualquer detalhe relevante para a sessão.': 'Use the notes to inform about injuries, preferences, or any relevant detail for the session.',
    'Após confirmar, verá uma mensagem de sucesso. Clique em <strong>"Voltar ao Lobby"</strong> para regressar ao painel principal.': 'After confirming, you will see a success message. Click <strong>"Back to Lobby"</strong> to return to the main dashboard.',
    'No <strong>Lobby</strong> encontrará o seu <strong>Dashboard</strong> com todas as reservas ativas. A partir daí pode <strong>cancelar</strong> qualquer sessão, se necessário.': 'In the <strong>Lobby</strong> you will find your <strong>Dashboard</strong> with all active bookings. From there you can <strong>cancel</strong> any session if necessary.',
    'Welcome ao seu Painel': 'Welcome to your Dashboard',
    'Aqui gere toda a sua operação. No <strong>Lobby</strong> verá um resumo com os <strong>próximos clientes</strong> agendados e terá acesso rápido a todas as ferramentas.': 'Here you manage your entire operation. In the <strong>Lobby</strong> you will see a summary with the <strong>upcoming clients</strong> scheduled and have quick access to all tools.',
    'Toque em <strong>"Gestão da Agenda"</strong> no Lobby para abrir o painel de controlo semanal.': 'Tap <strong>"Agenda Management"</strong> in the Lobby to open the weekly control panel.',
    'A agenda funciona <strong>por semanas</strong>. Use as setas <strong>&lt;</strong> e <strong>&gt;</strong> para navegar entre semanas e selecione o <strong>dia</strong> que pretende configurar.': 'The agenda works <strong>by weeks</strong>. Use the arrows <strong>&lt;</strong> and <strong>&gt;</strong> to navigate between weeks and select the <strong>day</strong> you want to configure.',
    'A agenda funciona <strong>por semanas</strong>. Use as setas <strong>&lt;</strong> e <strong>&gt;</strong> para navegar entre semanas e selecione o <strong>dia</strong> que pretende.': 'The agenda works <strong>by weeks</strong>. Use the arrows <strong>&lt;</strong> and <strong>&gt;</strong> to navigate between weeks and select the <strong>day</strong> you want.',
    'Ao selecionar um dia, aparecerão os <strong>horários das 06h às 20h</strong>. Toque em cada horário que pretende <strong>bloquear</strong> (marcar como indisponível).': 'Upon selecting a day, the <strong>times from 06h to 20h</strong> will appear. Tap each time you wish to <strong>block</strong> (mark as unavailable).',
    'Para remover um bloqueio, basta <strong>clicar novamente</strong> no horário bloqueado. O bloqueio será revertido.': 'To remove a block, simply <strong>click again</strong> on the blocked time. The block will be reversed.',
    '<strong>Bloquear todo o dia</strong> — Marca todos os horários de um dia como indisponíveis com um clique.': '<strong>Block entire day</strong> — Marks all times of a day as unavailable with one click.',
    '<strong>Limpar Bloqueios do Dia</strong> — Remove todos os bloqueios de um dia já publicado. Depois, publique novamente para aplicar.': '<strong>Clear Day Blocks</strong> — Removes all blocks of an already published day. Then, publish again to apply.',
    'Quando terminar de configurar os bloqueios, toque em <strong>"Publicar Agenda da Semana"</strong>. A semana inteira ficará <strong>aberta para reservas</strong> dos clientes.': 'When you finish configuring the blocks, tap <strong>"Publish Week Agenda"</strong>. The entire week will be <strong>open for client bookings</strong>.',
    'Ao publicar, todos os alunos receberão um <strong>email automático</strong> a informar que a semana está disponível para agendamento.': 'Upon publishing, all students will receive an <strong>automatic email</strong> informing them that the week is available for booking.',
    '<strong>Perfis</strong> — Veja a ficha completa de cada aluno: tarjeta de saúde, dados pessoais e histórico individual de reservas.': '<strong>Profiles</strong> — View the complete file of each student: health card, personal details, and individual booking history.',
    'Toque em <strong>"History"</strong> para aceder ao registo completo de <strong>todas as reservas</strong> de todos os clientes num só lugar.': 'Tap <strong>"History"</strong> to access the complete record of <strong>all bookings</strong> from all clients in one place.',
    'Sempre que um cliente <strong>fizer uma reserva</strong> ou <strong>cancelar uma sessão</strong>, receberá automaticamente um <strong>email de notificação</strong> com todos os detalhes.': 'Whenever a client <strong>makes a booking</strong> or <strong>cancels a session</strong>, you will automatically receive a <strong>notification email</strong> with all the details.',
    'Nome Completo': 'Full Name',
    'seu@email.com': 'your@email.com'
}

for file in glob.glob('en/*.html'):
    replace_in_file(file, tutorial_replacements)

print("Tutorials translated.")
